config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"

  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new', as: :log_in
  delete '/logout', to: 'sessions#destroy', as: :log_out

  resources :shoppings, :meals
  resources :staffs do
    member do
      get :add_admin
      get :remove_admin
    end
  end

  scope 'profile' do
    controller :profile do
      get :password
      put :update_password
    end
  end

  resources :departments, :goods, :watch_bills
  resources :books do
    member do
      put :circulate
    end
  end
  get "search", to:  "books#search"

  resources :projects, :quotation_categories, :quotations
  resources :quotation_lists do
    get :update_line_item
    member do
      get :construction_file
      # get :construction_contents
    end

    resources :quotation_list_items, only: [:show, :create, :update, :destroy] do
      member do
        get :add_line_item
        get :remove_line_item
      end
    end

    resources :construction_contents, only: [:index, :create, :destroy]
  end

  resources :roles

  resources :attendances, only: [:index] do
    collection do
      post :excel_import
    end
  end
end

app/models/staff.rb
class Staff < ApplicationRecord
  rolify
  authenticates_with_sorcery!

  has_many :shoppings
  has_many :meals
  has_many :goods
  belongs_to :department, optional: true
  has_many :watch_bills
  has_many :projects, foreign_key: :editor_id
  has_many :quotation_lists, foreign_key: :editor_id
  has_many :attendances

  attr_accessor :password, :password_confirmation

  PHONE_REGEX = /\A(\+86|86)?1\d{10}\z/
  EMAIL_REGEX = /\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*/

  validate :validate_email_or_phone, on: :create

  validates_presence_of :password, message: "密码不能为空",
    if: :need_validate_password
  validates_presence_of :password_confirmation, message: "密码确认不能为空",
    if: :need_validate_password
  validates_confirmation_of :password, message: "密码不一致",
    if: :need_validate_password
  validates_length_of :password, message: "密码最短为6位", minimum: 6,
    if: :need_validate_password

  validates :email, uniqueness: true
  validates :birthday, presence: true

  after_create :assign_default_role
  before_save :format_birthday

  def self.create_with_password(attr={})
    generated_password = attr[:phone]
    self.create(attr.merge(password: generated_password, password_confirmation: generated_password))
  end

  private
  def assign_default_role
    self.add_role(:staff) if self.roles.blank?
  end

  def need_validate_password
    self.new_record? ||
      (!self.password.nil? || !self.password_confirmation.nil?)
  end

  def format_birthday
    unless self.birthday.nil?
      self.birthday = DateTime.parse(self.birthday).strftime('%Y-%m-%d').to_s
    end
  end

  # TODO
  # 需要添加邮箱和手机号不能重复的校验
  def validate_email_or_phone
    if [self.email, self.phone].all? { |attr| attr.nil? }
      self.errors.add :base, "邮箱和手机号其中之一不能为空"
      return false
    else
      if self.phone.nil?
        if self.email.blank?
          self.errors.add :email, "邮箱不能为空"
          return false
        else
          unless self.email =~ EMAIL_REGEX
            self.errors.add :email, "邮箱格式不正确"
            return false
          end
        end
      else
        unless self.phone =~ PHONE_REGEX
          self.errors.add :phone, "手机号格式不正确"
          return false
        end

        # unless VerifyToken.available.find_by(phone: self.phone, token: self.token)
        #   self.errors.add :phone, "手机验证码不正确或者已过期"
        #   return false
        # end
      end
    end

    return true
  end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy, :add_admin, :remove_admin]
  before_action :find_departments, only: [:new, :create, :edit]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all.order("active DESC, created_at DESC")
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
    if current_user.id != params[:id].to_i
      flash[:error] = "你只能修改自己的信息."
      redirect_to staffs_path
    end
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.create_with_password(staff_params)

    if @staff.save
      flash[:success] = "信息录入成功。"
      redirect_to staffs_path
    else
      flash[:error] = "信息录入失败。"
      render :new
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    if @staff.update(staff_params)
      flash[:success] = "信息修改成功。"
      redirect_to @staff
    else
      flash[:warning] = "信息修改失败。"
      render :edit
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    if @staff.update_attribute(:active, false)
      flash[:success] = "信息修改成功。"
      redirect_to staffs_url
    end
  end

  def add_admin
    if @staff.add_role :admin
      flash[:success] = "设置管理员操作成功。"
      redirect_to staffs_path
    end
  end

  def remove_admin
    if @staff.remove_role :admin
      flash[:success] = "撤销管理员操作成功。"
      redirect_to staffs_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit!
    end

    def find_departments
      @departments = Department.all
    end
end

app/views/staffs/_form.html.erb
<div class="am-pagebody">
  <div class="card pd-20 pd-sm-40">
    <h6 class="card-body-title"><%= @staff.new_record? ? "新建" : "修改 ##{params[:id]}" %></h6>
    <p class="mg-b-20 mg-sm-b-30">每一位员的信息请尽可能完整的填写。</p>
    <%= form_with(model: staff, local: true, class: "form-layout") do |f| %>
      <% if @staff.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

          <ul>
          <% @staff.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="row mg-b-25">
        <div class="col-lg-4">
          <div class="form-group">
            <label class="form-control-label">工号: </label>
            <%= f.text_field :job_number, class: "form-control", placeholder: "输入员工工号" %>
          </div>
        </div>

        <div class="col-lg-4">
          <div class="form-group">
            <label class="form-control-label">姓名: <span class="tx-danger">*</span></label>
            <%= f.text_field :username, class: "form-control", placeholder: "输入员工姓名" %>
          </div>
        </div>

        <div class="col-lg-4">
          <div class="form-group">
            <label class="form-control-label">手机: <span class="tx-danger">*</span></label>
            <%= f.text_field :phone, class: "form-control", placeholder: "输入手机号" %>
          </div>
        </div>

        <div class="col-lg-4">
          <div class="form-group">
            <label class="form-control-label">Email: <span class="tx-danger">*</span></label>
            <%= f.text_field :email, class: "form-control", placeholder: "输入邮箱" %>
          </div>
        </div>

        <div class="col-lg-4">
          <div class="form-group">
            <label class="form-control-label">微信: <span class="tx-danger">*</span></label>
            <%= f.text_field :wechat, class: "form-control", placeholder: "输入微信" %>
          </div>
        </div>

        <div class="col-lg-4">
          <div class="form-group">
            <label class="form-control-label">生日: <span class="tx-danger">*</span></label>
            <%= f.text_field :birthday, class: "form-control", placeholder: "输入生日（20171225）" %>
          </div>
        </div>

        <div class="col-lg-4">
          <div class="form-group">
            <label class="form-control-label">昵称: </label>
            <%= f.text_field :nickname, class: "form-control", placeholder: "输入昵称" %>
          </div>
        </div>

        <div class="col-lg-4">
          <div class="form-group">
            <label class="form-control-label">QQ: </label>
            <%= f.text_field :qq, class: "form-control", placeholder: "输入QQ" %>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="form-group">
            <label class="form-control-label">性别: </label>
            <%= f.select :sex, [["男", "男"], ["女", "女"]], { include_blank: '请选择性别' }, class: "form-control" %>
          </div>
        </div>

        <div class="col-lg-4">
          <div class="form-group">
            <label class="form-control-label">部门: <span class="tx-danger">*</span></label>
            <%= f.select :department_id, @departments.collect { |d| [d.name, d.id] } , { include_blank: '请选择部门' }, class: "form-control" %>
          </div>
        </div>

        <div class="col-lg-4">
          <div class="form-group">
            <label class="form-control-label">试用期/月: </label>
            <%= f.number_field :probation_month, class: "form-control", placeholder: "输入试用期" %>
          </div>
        </div>

        <div class="col-lg-4">
          <div class="form-group">
            <label class="form-control-label">入职日期: </label>
            <div class="input-group">
              <span class="input-group-addon"><i class="icon ion-calendar tx-16 lh-0 op-6"></i></span>
              <%= f.date_field :job_date, class: "form-control fc-datepicker", placeholder: "MM/DD/YYYY" %>
            </div>
          </div>
        </div>

        <div class="col-lg-4">
          <div class="form-group">
            <label class="form-control-label">转正日期: </label>
            <div class="input-group">
              <span class="input-group-addon"><i class="icon ion-calendar tx-16 lh-0 op-6"></i></span>
              <%= f.date_field :official_date, class: "form-control fc-datepicker", placeholder: "MM/DD/YYYY" %>
            </div>
          </div>
        </div>
      </div>

      <div class="form-layout-footer">
        <button class="btn btn-info mg-r-5">确定</button>
        <%= link_to '取消', staffs_path, class: "btn btn-secondary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/staffs/edit.html.erb
<% provide(:title, "修改信息") %>

<%= render 'form', staff: @staff %>

app/views/staffs/index.html.erb
<% provide(:title, "员工列表") %>

<div class="am-pagebody">
  <div class="card pd-20">
    <h6 class="card-body-title">员工通讯录</h6>
    <p style="margin-bottom: 0;">记录员工基本信息。</p>
    <a href="<%= new_staff_path %>" class="btn btn-primary pd-lg-x-20 mg-l-auto">新建</a>
    <br>
    <div class="table-responsive">
      <table class="table table-hover table-bordered mg-b-0">
        <thead class="bg-info">
          <tr>
            <th>ID</th>
            <th>用户名</th>
            <th>性别</th>
            <th>手机</th>
            <th>微信</th>
            <th>生日</th>
            <th>部门</th>
            <th>转正日期</th>
            <th>在职状态</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <% @staffs.each do |s| %>
            <tr>
              <td><%= s.id %></td>
              <td><%= s.username %></td>
              <td><%= s.sex %></td>
              <td><%= s.phone %></td>
              <td><%= s.wechat %></td>
              <td><%= s.birthday %></td>
              <td><%= s.department&.name %></td>
              <td><%= s.official_date %></td>
              <td><%= raw(s.active? ? '<span class="tx-success">在职</span>' : '<span class="tx-danger">离职</span>') %></td>
              <td>
                <%= link_to "展示", staff_path(s), class: "btn btn-secondary btn-sm" %>
                <%= link_to "编辑", edit_staff_path(s), class: "btn btn-warning btn-sm" %>
                <%= link_to "删除", s, method: :delete, data: { confirm: '你确定要删除吗？' }, class: "btn btn-danger btn-sm" %>
                <% if current_user.has_role? :admin %>
                  <% unless s.has_role? :admin %>
                    <%= link_to "设置管理员", add_admin_staff_path(s), class: "btn btn-info btn-sm" %>
                  <% else %>
                    <%= link_to "取消管理员", remove_admin_staff_path(s), class: "btn btn-indigo btn-sm" %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/staffs/new.html.erb
<% provide(:title, "新建信息") %>

<%= render 'form', staff: @staff %>

app/views/staffs/show.html.erb
<% provide(:title, "查看信息") %>

<div class="am-pagebody">
  <div class="card pd-20 pd-sm-40">
    <h6 class="card-body-title"><span class="tx-danger"><%= @staff.username %></span>的详情</h6>
    <p class="mg-b-20 mg-sm-b-30">资料详情展示</p>
    <div class="row mg-b-20">
      <div class="col-md-3">
        <div class="card rounded-0">
          <div class="card-header card-header-default">
            员工工号
          </div>
          <div class="card-body bg-gray-200">
            <p class="mg-b-0"><%= @staff.job_number %></p>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card rounded-0">
          <div class="card-header card-header-default">
            员工姓名
          </div>
          <div class="card-body bg-gray-200">
            <p class="mg-b-0"><%= @staff.username %></p>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card rounded-0">
          <div class="card-header card-header-default">
            员工性别
          </div>
          <div class="card-body bg-gray-200">
            <p class="mg-b-0"><%= @staff.sex %></p>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card rounded-0">
          <div class="card-header card-header-default">
            员工手机号
          </div>
          <div class="card-body bg-gray-200">
            <p class="mg-b-0"><%= @staff.phone %></p>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card rounded-0">
          <div class="card-header card-header-default">
            员工邮箱
          </div>
          <div class="card-body bg-gray-200">
            <p class="mg-b-0"><%= @staff.email %></p>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card rounded-0">
          <div class="card-header card-header-default">
            员工微信
          </div>
          <div class="card-body bg-gray-200">
            <p class="mg-b-0"><%= @staff.wechat %></p>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card rounded-0">
          <div class="card-header card-header-default">
            员工生日
          </div>
          <div class="card-body bg-gray-200">
            <p class="mg-b-0"><%= @staff.birthday %></p>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card rounded-0">
          <div class="card-header card-header-default">
            员工昵称
          </div>
          <div class="card-body bg-gray-200">
            <p class="mg-b-0"><%= @staff.nickname %></p>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card rounded-0">
          <div class="card-header card-header-default">
            员工QQ
          </div>
          <div class="card-body bg-gray-200">
            <p class="mg-b-0"><%= @staff.qq %></p>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card rounded-0">
          <div class="card-header card-header-default">
            员工部门
          </div>
          <div class="card-body bg-gray-200">
            <p class="mg-b-0"><%= @staff.department&.name %></p>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card rounded-0">
          <div class="card-header card-header-default">
            试用期
          </div>
          <div class="card-body bg-gray-200">
            <p class="mg-b-0"><%= @staff.probation_month %></p>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card rounded-0">
          <div class="card-header card-header-default">
            入职日期
          </div>
          <div class="card-body bg-gray-200">
            <p class="mg-b-0"><%= @staff.job_date %></p>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card rounded-0">
          <div class="card-header card-header-default">
            转正日期
          </div>
          <div class="card-body bg-gray-200">
            <p class="mg-b-0"><%= @staff.official_date %></p>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card rounded-0">
          <div class="card-header card-header-default">
            离职日期
          </div>
          <div class="card-body bg-gray-200">
            <p class="mg-b-0"><%= @staff.dimission_date %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="form-layout-footer">
      <%= link_to '编辑', edit_staff_path(@staff), class: "btn btn-info mg-r-5" %>
      <%= link_to '返回', staffs_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>