config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"

  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new', as: :log_in
  delete '/logout', to: 'sessions#destroy', as: :log_out

  resources :shoppings, :meals
  resources :staffs do
    member do
      get :add_admin
      get :remove_admin
    end
  end

  scope 'profile' do
    controller :profile do
      get :password
      put :update_password
    end
  end

  resources :departments, :goods, :watch_bills
  resources :books do
    member do
      put :circulate
    end
  end
  get "search", to:  "books#search"

  resources :projects, :quotation_categories, :quotations
  resources :quotation_lists do
    get :update_line_item
    member do
      get :construction_file
      # get :construction_contents
    end

    resources :quotation_list_items, only: [:show, :create, :update, :destroy] do
      member do
        get :add_line_item
        get :remove_line_item
      end
    end

    resources :construction_contents, only: [:index, :create, :destroy]
  end

  resources :roles

  resources :attendances, only: [:index] do
    collection do
      post :excel_import
    end
  end
end

app/models/quotation_list.rb
class QuotationList < ApplicationRecord
  validates_presence_of :title, message: "项目名称不能为空"
  validates_presence_of :owner, message: "业主不能为空"
  validates_presence_of :address, message: "工程地址不能为空"
  validates_presence_of :maker, message: "制单人不能为空"

  belongs_to :editor, class_name: "Staff"
  has_many :quotation_list_items, dependent: :destroy
  has_many :quotation_list_line_items, through: :quotation_list_items
  has_many :construction_contents

  validates :status, inclusion: { in: %w(draft), message: "%{status} 不是一个合法的状态" }



end

app/controllers/quotation_lists_controller.rb
class QuotationListsController < ApplicationController
  before_action :set_quotation_list, only: [
    :show, :edit, :update, :destroy, :add_list_item, :remove_list_item, :construction_file, :construction_contents
  ]

  # GET /quotation_lists
  # GET /quotation_lists.json
  def index
    @quotation_lists = QuotationList.page(params[:page] || 1).per(params[:per_page] || 15).order("created_at DESC")
  end

  # GET /quotation_lists/1
  # GET /quotation_lists/1.json
  def show
    # @q_categories = QuotationCategory.find_by_title('爱上家装饰报价清单').children.order('weight DESC')
    @new_list_item = @quotation_list.quotation_list_items.new
    @list_item = @quotation_list.quotation_list_items.order("weight ASC")
    @root_categories = QuotationCategory.roots.order(created_at: "ASC")

    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = "attachment; filename='爱上家标准报价 #{Time.now.strftime('%F %R')}.xlsx'"
      }
    end
  end

  # GET /quotation_lists/new
  def new
    @quotation_list = current_user.quotation_lists.new
  end

  # GET /quotation_lists/1/edit
  def edit
    authorize(@quotation_list, :can_edit?)
  end

  # POST /quotation_lists
  # POST /quotation_lists.json
  def create
    @quotation_list = current_user.quotation_lists.new(quotation_list_params)

    respond_to do |format|
      if @quotation_list.save
        format.html { redirect_to @quotation_list, notice: 'Quotation list was successfully created.' }
        format.json { render :show, status: :created, location: @quotation_list }
      else
        format.html { render :new }
        format.json { render json: @quotation_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotation_lists/1
  # PATCH/PUT /quotation_lists/1.json
  def update
    authorize(@quotation_list, :can_update?)
    quotation_list_params["in_province"] = "off" if quotation_list_params["in_province"].nil?

    respond_to do |format|
      if @quotation_list.update(quotation_list_params)
        format.html { redirect_to @quotation_list, notice: 'Quotation list was successfully updated.' }
        format.json { render :show, status: :ok, location: @quotation_list }
      else
        format.html { render :edit }
        format.json { render json: @quotation_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotation_lists/1
  # DELETE /quotation_lists/1.json
  def destroy
    authorize(@quotation_list, :can_destroy?)
    @quotation_list.destroy
    respond_to do |format|
      format.html { redirect_to quotation_lists_url, notice: 'Quotation list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_line_item
    line_item_id =  params["id"].strip
    line_item_params = {}
    if params["项目名称"]
      line_item_params[:name] = params["项目名称"].gsub(" ","")
    elsif params["单位"]
      line_item_params[:unit] = params["单位"].gsub(" ","")
    elsif params["数量"]
      line_item_params[:quantity] = params["数量"].gsub(" ","")
    elsif params["材料费"]
      line_item_params[:material_costs] = params["材料费"].gsub(" ","")
    elsif params["人工费"]
      line_item_params[:labor_costs] = params["人工费"].gsub(" ","")
    end
    QuotationListLineItem.find(line_item_id).update_attributes(line_item_params)
  end

  def construction_file
    @list_item = @quotation_list.quotation_list_items.order("weight DESC")
    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = "attachment; filename='爱上家标准报价 #{Time.now.strftime('%F %R')}.xlsx'"
      }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quotation_list
      @quotation_list = QuotationList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quotation_list_params
      params.require(:quotation_list).permit!
    end
end

app/helpers/quotation_lists_helper.rb
module QuotationListsHelper
end

app/views/quotation_lists/_form.html.erb
<div class="am-pagebody">
  <div class="card pd-20 pd-sm-40">
    <h6 class="card-body-title"><%= @quotation_list.new_record? ? "新建" : "修改 ##{@quotation_list.title}#" %></h6>
    <% if quotation_list.errors.any? %>
      <div id="error_explanation">
        <h2>保存时发生以下错误:</h2>

        <ul>
        <% quotation_list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_with(model: quotation_list, local: true, class: "form-layout") do |f| %>
      <div class="row mg-b-25">
        <div class="col-lg-3">
          <div class="form-group">
            <label class="form-control-label">项目名称: <span class="tx-danger">*</span></label>
            <%= f.text_field :title, class: "form-control" %>
          </div>
        </div>

        <div class="col-lg-3">
          <div class="form-group">
            <label class="form-control-label">施工日期: <span class="tx-danger">*</span></label>
            <%= f.date_field :commencement_date, class: "form-control" %>
          </div>
        </div>

        <div class="col-lg-6">
          <div class="form-group">
            <label class="form-control-label">施工地址: <span class="tx-danger">*</span></label>
            <%= f.text_field :address, class: "form-control" %>
          </div>
        </div>

        <div class="col-lg-3">
          <div class="form-group">
            <label class="form-control-label">客户姓名: <span class="tx-danger">*</span></label>
            <%= f.text_field :owner, class: "form-control" %>
          </div>
        </div>

        <div class="col-lg-3">
          <div class="form-group">
            <label class="form-control-label">客户电话: <span class="tx-danger">*</span></label>
            <%= f.text_field :owner_phone, class: "form-control" %>
          </div>
        </div>

        <div class="col-lg-3">
          <div class="form-group">
            <label class="form-control-label">施工负责人: <span class="tx-danger">*</span></label>
            <%= f.text_field :construction_manager, class: "form-control" %>
          </div>
        </div>

        <div class="col-lg-3">
          <div class="form-group">
            <label class="form-control-label">施工负责人电话: <span class="tx-danger">*</span></label>
            <%= f.text_field :construction_manager_phone, class: "form-control" %>
          </div>
        </div>

        <div class="col-lg-3">
          <div class="form-group">
            <label class="form-control-label">设    计: <span class="tx-danger">*</span></label>
            <%= f.text_field :design, class: "form-control" %>
          </div>
        </div>

        <div class="col-lg-3">
          <div class="form-group">
            <label class="form-control-label">设计联络电话: <span class="tx-danger">*</span></label>
            <%= f.text_field :design_phone, class: "form-control" %>
          </div>
        </div>

        <div class="col-lg-3">
          <div class="form-group">
            <label class="form-control-label">预算: <span class="tx-danger">*</span></label>
            <%= f.number_field :budget, class: "form-control" %>
          </div>
        </div>

        <div class="col-lg-3">
          <div class="form-group">
            <label class="form-control-label">施工面积: <span class="tx-danger">*</span></label>
            <%= f.number_field :area, class: "form-control" %>
          </div>
        </div>

        <div class="col-lg-3">
          <div class="form-group">
            <label class="form-control-label">制单人: <span class="tx-danger">*</span></label>
            <%= f.text_field :maker, class: "form-control", step: :any %>
          </div>
        </div>

        <div class="col-lg-3">
          <label class="form-control-label">省外？: <span class="tx-danger">*</span></label>
          <label class="ckbox">
            <input type="checkbox" name="quotation_list[in_province]" <%= "checked" if @quotation_list.in_province %>><span>工程所在地是否在省外？</span>
          </label>
        </div>
      </div>
      <div class="form-layout-footer">
        <%= f.submit "确 定", class: "btn btn-info" %>
      </div>
    <% end %>
  </div>
</div>

app/views/quotation_lists/edit.html.erb
<% provide(:title, "修改报价清单") %>

<%= render 'form', quotation_list: @quotation_list %>

app/views/quotation_lists/index.html.erb
<% provide(:title, "爱上家标准清单") %>
<div class="am-pagebody">
  <div class="card pd-20">
    <h6 class="card-body-title">标准报价</h6>
    <p class="mg-b-20 mg-sm-b-30">爱上家装饰报价清单</p>
    <div class="mg-t-10 mg-md-t-0">
      <a href="<%= new_quotation_list_path %>" class="btn btn-primary">添加</a>
    </div>
    <br>
    <div class="table-responsive">
      <table class="table table-hover table-bordered mg-b-0">
        <thead class="bg-info">
          <tr>
            <th>序号</th>
            <th>项目名称</th>
            <th>客户姓名</th>
            <th>工程地址</th>
            <th>制单人</th>
            <th>操作</th>
          </tr>
        </thead>
        <% @quotation_lists.each do |quotation_list| %>
          <tr>
            <td><%= quotation_list.id %></td>
            <td><%= quotation_list.title %></td>
            <td><%= quotation_list.owner %></td>
            <td><%= quotation_list.address %></td>
            <td><%= quotation_list.maker %></td>
            <td>
              <%= link_to "下载", quotation_list_path(quotation_list, format: :xlsx), title: "下载设计文件"%> |
              <%#= link_to construction_file_quotation_list_path(quotation_list, format: :xlsx), title: "下载工程文件" do %>
                <!-- <i class="icon icon ion-settings"></i>Excel -->
              <%# end %>
              <%= link_to '项目信息', edit_quotation_list_path(quotation_list) %> |
              <%= link_to '施工内容', quotation_list_construction_contents_path(quotation_list.id) %> |
              <%= link_to '报价清单', quotation_list %> |
              <%= link_to '删除', quotation_list, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
      </table>
      <br>
      <%= paginate @quotation_lists %>
    </div>
  </div>
</div>

app/views/quotation_lists/new.html.erb
<% provide(:title, "新建报价清单") %>

<%= render 'form', quotation_list: @quotation_list %>

app/views/quotation_lists/show.html.erb
<% provide(:title, "查看报价清单") %>
<%= content_for :stylesheets do %>
  <style>
    .item-select2 {
      width: 200px;
    }
    tr.border_bottom th {
      border-bottom:1pt solid white !important;
    }
  </style>
<% end %>

<div class="am-pagebody">
  <div class="card pd-20">
    <h6 class="card-body-title">查看报价清单</h6>
    <p class="mg-b-20 mg-sm-b-30">
      <%= @quotation_list.title %> 报价清单
      <small>
        <%= link_to quotation_list_path(@quotation_list, format: :xlsx) do %>
          <i class="icon ion-arrow-down-a"></i>下载 Excel
        <% end %>
      </small>
    </p>
    <div class="table-responsive">
      <table class="table table-hover table-bordered mg-b-0">
        <thead class="bg-primary">
          <tr>
            <th>项目名称</th>
            <th>业主</th>
            <th>工程地址</th>
            <th>制单人</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @quotation_list.title %></td>
            <td><%= @quotation_list.owner %></td>
            <td><%= @quotation_list.address %></td>
            <td><%= @quotation_list.maker %></td>
            <td>
              <button class="btn btn-outline-primary btn-block btn-sm" data-toggle="modal" data-target="#addQuotationListItem">
                <i class="fa fa-plus"></i> 添加报价项
              </button>
            </td>
          </tr>
        </tbody>
      </table>

      <!-- item modal -->
      <div id="addQuotationListItem" class="modal fade">
        <div class="modal-dialog modal-dialog-vertical-center" role="document">
          <div class="modal-content tx-size-sm">
            <div class="modal-header pd-x-20">
              <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold">装饰报价条目</h6>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <%= form_for([@quotation_list, @new_list_item]) do |f| %>
              <div class="modal-body pd-20">
                <div class="d-md-flex pd-y-20 pd-md-y-0">
                  <div class="d-flex">
                    <div class="form-group mg-b-0">
                      <label>类目: <span class="tx-danger">*</span></label>
                      <%= f.text_field :title, class: "form-control wd-220", placeholder: "请输入类目分组名称", required: true %>
                    </div><!-- form-group -->
                    <div class="form-group mg-b-0 mg-l-20">
                      <label>权重: <small>（数字越大越靠前）</small></label>
                      <%= f.text_field :weight, class: "form-control wd-220", placeholder: "请输入整数" %>
                    </div><!-- form-group -->
                  </div>
                </div>
              </div><!-- modal-body -->
              <div class="modal-footer">
                <button type="submit" class="btn btn-info pd-x-20">保存</button>
                <button type="button" class="btn btn-secondary pd-x-20" data-dismiss="modal">取消</button>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <% @list_item.each do |item| %>
        <table class="table table-hover table-bordered mg-b-0 _tabledit">
          <thead class="bg-info">
            <tr class="border_bottom">
              <th colspan="7">
                <%= form_tag quotation_list_quotation_list_item_path(@quotation_list, item.id), method: :put do %>
                  <input type="text" name="quotation_list_item[title]" value="<%= item.title %>" />
                  <input type="text" name="quotation_list_item[weight]" value="<%= item.weight %>" placeholder="请输入整数">
                  <%= submit_tag "更新" %>
                <% end %>
              </th>
              <th>
                <%= link_to "删除", quotation_list_quotation_list_item_path(@quotation_list, item.id), method: :delete, data: { confirm: '你确定要删除吗？' }, class: "tx-white hover-white-8" %>
              </th>
            </tr>
            <tr>
              <th style="display: none;">ID</th>
              <th>项目编码</th>
              <th>项目名称</th>
              <th>单位</th>
              <th>数量</th>
              <th>材料费</th>
              <th>人工费</th>
              <th>合计</th>
              <th class="tabledit-toolbar-column">
                <%= link_to quotation_list_quotation_list_item_path(@quotation_list, item.id), class: "tx-warning hover-white-8" do %>
                  <i class="icon ion-clipboard"></i>去添加
                <% end %>
              </th>
            </tr>
          </thead>
          <tbody>
            <% item.quotation_list_line_items.each do |line_item| %>
              <tr>
                <td style="display: none;">
                  <%= line_item.id %>
                </td>
                <td>
                  <%= line_item.code.split("_").last %>
                </td>
                <td>
                  <%= line_item.name %>
                </td>
                <td class="tx-12">
                  <%= line_item.unit %>
                </td>
                <td class="tx-12">
                  <%= line_item.quantity %>
                </td>
                <td class="tx-12">
                  <%= line_item.material_costs %>
                </td>
                <td class="tx-12">
                  <%= line_item.labor_costs %>
                </td>
                <td class="tx-12">
                  <%= line_item.total_amount %>
                </td>
                <td class="pd-l-20 tx-center">
                  <%= link_to remove_line_item_quotation_list_quotation_list_item_path(@quotation_list.id, item.id, line_item_id: line_item.id), data: { confirm: '你确定要删除吗？' }, class: "btn btn-outline-danger btn-block btn-sm" do %>
                    <i class="icon ion-backspace"></i> 删除
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

<%= content_for :javascripts do %>
  <script>
    $('._tabledit').Tabledit({
      url: "<%= quotation_list_update_line_item_path(@quotation_list.id) %>",
      rowIdentifier: 'data-id',
      eventType: 'dblclick',
      columns: {
        identifier: [0, 'id'],
        editable: [[2, '项目名称'], [3, '单位'], [4, '数量']]
      },
      editButton: false,
      deleteButton:false,
      onSuccess: function() {
        location.reload();;
      }
    });
  </script>
<% end %>