config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"

  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new', as: :log_in
  delete '/logout', to: 'sessions#destroy', as: :log_out

  resources :shoppings, :meals
  resources :staffs do
    member do
      get :add_admin
      get :remove_admin
    end
  end

  scope 'profile' do
    controller :profile do
      get :password
      put :update_password
    end
  end

  resources :departments, :goods, :watch_bills
  resources :books do
    member do
      put :circulate
    end
  end
  get "search", to:  "books#search"

  resources :projects, :quotation_categories, :quotations
  resources :quotation_lists do
    get :update_line_item
    member do
      get :construction_file
      # get :construction_contents
    end

    resources :quotation_list_items, only: [:show, :create, :update, :destroy] do
      member do
        get :add_line_item
        get :remove_line_item
      end
    end

    resources :construction_contents, only: [:index, :create, :destroy]
  end

  resources :roles

  resources :attendances, only: [:index] do
    collection do
      post :excel_import
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord

  def self.import(file)
    spreadsheet = Roo::Spreadsheet.open(file.path)
    header = %w(date_at name account department rule times_count work_hours approval status calibration start_type start_work start_sta end_type end_work end_sta)
    daily = spreadsheet.sheet(0)
    (4..daily.last_row).each do |i|
      row = Hash[[header, daily.row(i)[0,16]].transpose]
      %w(start_type start_sta end_type end_sta).each { |k| row.delete(k) }
      record = find_by(date_at: row["date_at"], name: row["name"]) || new
      record.attributes = row.to_hash
      record.save!
    end
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :staff, foreign_key: :borrow_id, optional: true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :staff
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :staff, optional: true
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :staff, optional: true

  validates :staff_id, presence: true

  def self.book_limit(current_user)
    current_user.meals.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day, active: true).count
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :assistant, class_name: "Staff", foreign_key: :assistant_id
  belongs_to :level2_assistant, class_name: "Staff", foreign_key: :level2_assistant_id
  belongs_to :level3_assistant, class_name: "Staff", foreign_key: :level3_assistant_id
end

app/models/quotation.rb
class Quotation < ApplicationRecord

  validates :quotation_category0_id, presence: { message: "标准分类不能为空。" }
  validates :quotation_category1_id, presence: { message: "工程分类不能为空。" }
  validates :quotation_category2_id, presence: { message: "设计分类不能为空。" }
  validates :code, presence: { message: "项目编码不能为空。" }
  validates :name, presence: { message: "项目名称不能为空。" }
  validates :material_costs, presence: { message: "材料费不能为空。" }
  validates :labor_costs, presence: { message: "人工费不能为空。" }
  validates :remark, presence: { message: "描述不能为空。" }

  belongs_to :quotation_category, optional: true
end

app/models/quotation_list.rb
class QuotationList < ApplicationRecord
  validates_presence_of :title, message: "项目名称不能为空"
  validates_presence_of :owner, message: "业主不能为空"
  validates_presence_of :address, message: "工程地址不能为空"
  validates_presence_of :maker, message: "制单人不能为空"

  belongs_to :editor, class_name: "Staff"
  has_many :quotation_list_items, dependent: :destroy
  has_many :quotation_list_line_items, through: :quotation_list_items
  has_many :construction_contents

  validates :status, inclusion: { in: %w(draft), message: "%{status} 不是一个合法的状态" }



end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :staffs, :join_table => :staffs_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/shopping.rb
class Shopping < ApplicationRecord
  belongs_to :staff, optional: true

  validates :buyer, :total, :shopping_date, presence: true
end

app/models/staff.rb
class Staff < ApplicationRecord
  rolify
  authenticates_with_sorcery!

  has_many :shoppings
  has_many :meals
  has_many :goods
  belongs_to :department, optional: true
  has_many :watch_bills
  has_many :projects, foreign_key: :editor_id
  has_many :quotation_lists, foreign_key: :editor_id
  has_many :attendances

  attr_accessor :password, :password_confirmation

  PHONE_REGEX = /\A(\+86|86)?1\d{10}\z/
  EMAIL_REGEX = /\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*/

  validate :validate_email_or_phone, on: :create

  validates_presence_of :password, message: "密码不能为空",
    if: :need_validate_password
  validates_presence_of :password_confirmation, message: "密码确认不能为空",
    if: :need_validate_password
  validates_confirmation_of :password, message: "密码不一致",
    if: :need_validate_password
  validates_length_of :password, message: "密码最短为6位", minimum: 6,
    if: :need_validate_password

  validates :email, uniqueness: true
  validates :birthday, presence: true

  after_create :assign_default_role
  before_save :format_birthday

  def self.create_with_password(attr={})
    generated_password = attr[:phone]
    self.create(attr.merge(password: generated_password, password_confirmation: generated_password))
  end

  private
  def assign_default_role
    self.add_role(:staff) if self.roles.blank?
  end

  def need_validate_password
    self.new_record? ||
      (!self.password.nil? || !self.password_confirmation.nil?)
  end

  def format_birthday
    unless self.birthday.nil?
      self.birthday = DateTime.parse(self.birthday).strftime('%Y-%m-%d').to_s
    end
  end

  # TODO
  # 需要添加邮箱和手机号不能重复的校验
  def validate_email_or_phone
    if [self.email, self.phone].all? { |attr| attr.nil? }
      self.errors.add :base, "邮箱和手机号其中之一不能为空"
      return false
    else
      if self.phone.nil?
        if self.email.blank?
          self.errors.add :email, "邮箱不能为空"
          return false
        else
          unless self.email =~ EMAIL_REGEX
            self.errors.add :email, "邮箱格式不正确"
            return false
          end
        end
      else
        unless self.phone =~ PHONE_REGEX
          self.errors.add :phone, "手机号格式不正确"
          return false
        end

        # unless VerifyToken.available.find_by(phone: self.phone, token: self.token)
        #   self.errors.add :phone, "手机验证码不正确或者已过期"
        #   return false
        # end
      end
    end

    return true
  end
end

app/models/watch_bill.rb
class WatchBill < ApplicationRecord
  belongs_to :staff, optional: true

  validates :duty_date, :dayshift, :nightshift, presence: true
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/shoppings_helper.rb
module ShoppingsHelper
end

app/views/shared/_flash_messages.html.erb
<% if flash.any? %>
  <% content_for :javascripts do %>
    <% flash.map do |key, message| %>
      <script>
        msg_show('<%= flashes_class(key) %>','<%= message %>','<%= t :warm_prompt %>：');
      </script>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<div class="am-footer">
  <span>Copyright &copy;. All Rights Reserved. AiShangJia.</span>
  <span>Created by: R&D, Inc.</span>
</div>

app/views/shared/_header.html.erb
<div class="am-header">
  <div class="am-header-left">
    <a id="naviconLeft" href="" class="am-navicon d-none d-lg-flex"><i class="icon ion-navicon-round"></i></a>
    <a id="naviconLeftMobile" href="" class="am-navicon d-lg-none"><i class="icon ion-navicon-round"></i></a>
    <a href="index.html" class="am-logo">心胜OA系统</a>
  </div>
  <!-- am-header-left -->
  <div class="am-header-right">
    <div class="dropdown dropdown-notification">
      <a href="" class="nav-link pd-x-7 pos-relative" data-toggle="dropdown">
        <i class="icon ion-ios-bell-outline tx-24"></i>
        <!-- start: if statement -->
        <span class="square-8 bg-danger pos-absolute t-15 r-0 rounded-circle"></span>
        <!-- end: if statement -->
      </a>
      <!-- <div class="dropdown-menu wd-300 pd-0-force">
        <div class="dropdown-menu-header">
          <label>Notifications</label>
          <a href="">Mark All as Read</a>
        </div>
        <div class="media-list">
          <a href="" class="media-list-link read">
            <div class="media pd-x-20 pd-y-15">
              <img src="<%#= image_path('img8.jpg') %>" class="wd-40 rounded-circle" alt="">
              <div class="media-body">
                <p class="tx-13 mg-b-0"><strong class="tx-medium">Suzzeth Bungaos</strong> tagged you and 18 others in a post.</p>
                <span class="tx-12">October 03, 2017 8:45am</span>
              </div>
            </div>
          </a>
          <a href="" class="media-list-link read">
            <div class="media pd-x-20 pd-y-15">
              <img src="<%#= image_path('img9.jpg') %>" class="wd-40 rounded-circle" alt="">
              <div class="media-body">
                <p class="tx-13 mg-b-0"><strong class="tx-medium">Mellisa Brown</strong> appreciated your work <strong class="tx-medium">The Social Network</strong></p>
                <span class="tx-12">October 02, 2017 12:44am</span>
              </div>
            </div>
          </a>
          <div class="media-list-footer">
            <a href="" class="tx-12"><i class="fa fa-angle-down mg-r-5"></i> Show All Notifications</a>
          </div>
        </div>
      </div> -->
      <!-- dropdown-menu -->
    </div>
    <!-- dropdown -->
    <div class="dropdown dropdown-profile">
      <a href="" class="nav-link nav-link-profile" data-toggle="dropdown">
            <img src="<%= image_path('avatar.png') %>" class="wd-32 rounded-circle" alt="">
            <span class="logged-name"><span class="hidden-xs-down"><%= current_user&.username %></span> <i class="fa fa-angle-down mg-l-3"></i></span>
          </a>
      <div class="dropdown-menu wd-200">
        <ul class="list-unstyled user-profile-nav">
          <li><a href="<%= password_path %>"><i class="icon ion-ios-person-outline"></i> 修改密码</a></li>
          <li>
            <%= link_to log_out_path, method: 'DELETE' do %><i class="icon ion-power"></i> 退出<% end %>
          </li>
        </ul>
      </div>
      <!-- dropdown-menu -->
    </div>
    <!-- dropdown -->
  </div>
  <!-- am-header-right -->
</div>

app/views/shared/_sidebar.html.erb
<div class="am-sideleft">
  <ul class="nav am-sideleft-tab">
    <li class="nav-item">
      <a href="#mainMenu" class="nav-link active"><i class="icon ion-ios-home-outline tx-24"></i></a>
    </li>
    <li class="nav-item">
      <a href="#emailMenu" class="nav-link"><i class="icon ion-ios-email-outline tx-24"></i></a>
    </li>
    <li class="nav-item">
      <a href="#chatMenu" class="nav-link"><i class="icon ion-ios-chatboxes-outline tx-24"></i></a>
    </li>
    <li class="nav-item">
      <a href="#settingMenu" class="nav-link"><i class="icon ion-ios-gear-outline tx-24"></i></a>
    </li>
  </ul>
  <div class="tab-content">
    <div id="mainMenu" class="tab-pane active">
      <ul class="nav am-sideleft-menu">
        <li class="nav-item">
          <a href="<%= root_path %>" class="nav-link <%= 'active' if current_page?('/') %>">
            <i class="icon ion-ios-home-outline"></i>
            <span>首页</span>
          </a>
        </li>

        <li class="nav-item">
          <a href="" class="nav-link with-sub <%= 'active show-sub' if (controller_name.gsub('_', '-') == 'quotations') || (controller_name.gsub('_', '-') == 'quotation-categories') || (controller_name.gsub('_', '-') == 'quotation-lists') || (controller_name.gsub('_', '-') == 'quotation-list-items') || (controller_name.gsub('_', '-') == 'construction-contents')
          %>"">
            <i class="icon fa fa-cube"></i>
            <span>项目工程管理</span>
          </a>
          <ul class="nav-sub">
            <li class="nav-item">
              <a href="<%= quotation_lists_path %>" class="nav-link <%= 'active' if (controller_name.gsub('_', '-') == 'quotation-lists') || (controller_name.gsub('_', '-') == 'quotation-list-items') || (controller_name.gsub('_', '-') == 'construction-contents') %>">装饰报价清单</a>
            </li>

            <li class="nav-item">
              <a href="<%= quotations_path %>" class="nav-link <%= 'active' if controller_name.gsub('_', '-') == 'quotations' %>">装饰报价总表</a>
            </li>

            <li class="nav-item">
              <a href="<%= quotation_categories_path %>" class="nav-link <%= 'active' if controller_name.gsub('_', '-') == 'quotation-categories' %>">装饰报价分类</a>
            </li>
          </ul>
        </li>

        <li class="nav-item">
          <a href="" class="nav-link with-sub <%= 'active show-sub' if (controller_name.gsub('_', '-') == 'attendances') || (controller_name.gsub('_', '-') == 'watch-bills') %>"">
            <i class="icon fa fa-calendar"></i>
            <span>日常管理</span>
          </a>
          <ul class="nav-sub">
            <li class="nav-item">
              <a href="<%= attendances_path %>" class="nav-link <%= 'active' if controller_name.gsub('_', '-') == 'attendances' %>">考勤管理</a>
            </li>
            <li class="nav-item">
              <a href="<%= watch_bills_path %>" class="nav-link <%= 'active' if controller_name.gsub('_', '-') == 'watch-bills' %>">值班管理</a>
            </li>
          </ul>
        </li>


        <li class="nav-item">
          <a href="" class="nav-link with-sub <%= 'active show-sub' if (controller_name.gsub('_', '-') == 'shoppings') || (controller_name.gsub('_', '-') == 'goods') || (controller_name.gsub('_', '-') == 'meals') %>"">
            <i class="icon fa fa-spoon"></i>
            <span>订餐管理</span>
          </a>
          <ul class="nav-sub">
            <li class="nav-item">
              <a href="<%= meals_path %>" class="nav-link <%= 'active' if controller_name.gsub('_', '-') == 'meals' %>">订餐报名</a>
            </li>

            <li class="nav-item">
              <a href="<%= shoppings_path %>" class="nav-link <%= 'active' if controller_name.gsub('_', '-') == 'shoppings' %>">每日菜品</a>
            </li>

            <li class="nav-item">
              <a href="<%= goods_path %>" class="nav-link <%= 'active' if controller_name.gsub('_', '-') == 'goods' %>"> 柴米油盐</a>
            </li>
          </ul>
        </li>

        <li class="nav-item">
          <a href="<%= books_path %>" class="nav-link <%= 'active' if controller_name.gsub('_', '-') == 'books' %>">
            <i class="icon fa fa-book"></i>
            <span>图书管理</span>
          </a>
        </li>

        <li class="nav-item">
          <a href="<%= staffs_path %>" class="nav-link <%= 'active' if controller_name.gsub('_', '-') == 'staffs' %>">
            <i class="icon ion-person-stalker"></i>
            <span>员工通讯录</span>
          </a>
        </li>

        <% if current_user.has_role? :admin %>
          <li class="nav-item">
            <a href="" class="nav-link with-sub <%= 'active show-sub' if (controller_name.gsub('_', '-') == 'departments') || (controller_name.gsub('_', '-') == 'roles') %>"">
              <i class="icon fa fa-cog"></i>
              <span>设置</span>
            </a>
            <ul class="nav-sub">
              <li class="nav-item">
                <a href="<%= departments_path %>" class="nav-link <%= 'active' if controller_name.gsub('_', '-') == 'departments' %>">部门设置</a>
              </li>

              <li class="nav-item">
                <a href="<%= roles_path %>" class="nav-link <%= 'active' if controller_name.gsub('_', '-') == 'roles' %>">权限设置</a>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
    <!-- #mainMenu -->
    <div id="emailMenu" class="tab-pane">
      <div class="pd-x-20 pd-y-10">
        <a href="" class="btn btn-orange btn-block btn-compose">Compose Email</a>
      </div>
      <ul class="nav am-sideleft-menu">
        <li class="nav-item">
          <a href="page-inbox.html" class="nav-link">
                <i class="icon ion-ios-filing-outline"></i>
                <span>Inbox</span>
              </a>
        </li>
        <!-- nav-item -->
        <li class="nav-item">
          <a href="page-inbox.html" class="nav-link">
                <i class="icon ion-ios-filing-outline"></i>
                <span>Drafts</span>
              </a>
        </li>
        <!-- nav-item -->
        <li class="nav-item">
          <a href="page-inbox.html" class="nav-link">
                <i class="icon ion-ios-paperplane-outline"></i>
                <span>Sent</span>
              </a>
        </li>
        <!-- nav-item -->
        <li class="nav-item">
          <a href="page-inbox.html" class="nav-link">
                <i class="icon ion-ios-trash-outline"></i>
                <span>Trash</span>
              </a>
        </li>
        <!-- nav-item -->
        <li class="nav-item">
          <a href="page-inbox.html" class="nav-link">
                <i class="icon ion-ios-filing-outline"></i>
                <span>Spam</span>
              </a>
        </li>
        <!-- nav-item -->
      </ul>
      <label class="pd-x-20 tx-uppercase tx-11 mg-t-10 tx-orange mg-b-0 tx-medium">My Folder</label>
      <ul class="nav am-sideleft-menu">
        <li class="nav-item">
          <a href="page-inbox.html" class="nav-link">
                <i class="icon ion-ios-folder-outline"></i>
                <span>Updates</span>
              </a>
        </li>
        <!-- nav-item -->
        <li class="nav-item">
          <a href="page-inbox.html" class="nav-link">
                <i class="icon ion-ios-folder-outline"></i>
                <span>Social</span>
              </a>
        </li>
        <!-- nav-item -->
        <li class="nav-item">
          <a href="page-inbox.html" class="nav-link">
                <i class="icon ion-ios-folder-outline"></i>
                <span>Promotions</span>
              </a>
        </li>
        <!-- nav-item -->
      </ul>
    </div>
    <!-- #emailMenu -->
    <div id="chatMenu" class="tab-pane">
      <div class="chat-search-bar">
        <input type="search" class="form-control wd-150" placeholder="Search chat...">
        <button class="btn btn-secondary"><i class="fa fa-search"></i></button>
      </div>
      <!-- chat-search-bar -->
      <label class="pd-x-15 tx-uppercase tx-11 mg-t-20 tx-orange mg-b-10 tx-medium">Recent Chat History</label>
      <div class="list-group list-group-chat">
        <a href="#" class="list-group-item">
          <div class="d-flex align-items-center">
            <img src="<%= image_path('img6.jpg') %>" class="wd-32 rounded-circle" alt="">
            <div class="mg-l-10">
              <h6>Russell M. Evans</h6>
              <span>Tuesday, 10:33am</span>
            </div>
          </div>
          <!-- d-flex -->
          <p>Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain...</p>
        </a>
        <!-- list-group-item -->
        <a href="#" class="list-group-item">
          <div class="d-flex align-items-center">
            <img src="<%= image_path('img7.jpg') %>" class="wd-32 rounded-circle" alt="">
            <div class="mg-l-10">
              <h6>James F. Sears</h6>
              <span>Monday, 4:21pm</span>
            </div>
          </div>
          <!-- d-flex -->
          <p>But who has any right to find fault with a man who chooses to enjoy a pleasure that has...</p>
        </a>
        <!-- list-group-item -->
        <a href="#" class="list-group-item">
          <div class="d-flex align-items-center">
            <img src="<%= image_path('img8.jpg') %>" class="wd-32 rounded-circle" alt="">
            <div class="mg-l-10">
              <h6>Sharon R. Rowe</h6>
              <span>Sunday, 7:45pm</span>
            </div>
          </div>
          <!-- d-flex -->
          <p>But I must explain to you how all this mistaken idea of denouncing pleasure and praising...</p>
        </a>
        <!-- list-group-item -->
        <a href="#" class="list-group-item">
          <div class="d-flex align-items-center">
            <img src="<%= image_path('img9.jpg') %>" class="wd-32 rounded-circle" alt="">
            <div class="mg-l-10">
              <h6>Ruby M. Martin</h6>
              <span>Sunday, 7:45pm</span>
            </div>
          </div>
          <!-- d-flex -->
          <p>But I must explain to you how all this mistaken idea of denouncing pleasure and praising...</p>
        </a>
        <!-- list-group-item -->
        <a href="#" class="list-group-item">
          <div class="d-flex align-items-center">
            <img src="<%= image_path('img10.jpg') %>" class="wd-32 rounded-circle" alt="">
            <div class="mg-l-10">
              <h6>Joslyn C. Mayo</h6>
              <span>Sunday, 7:45pm</span>
            </div>
          </div>
          <!-- d-flex -->
          <p>But I must explain to you how all this mistaken idea of denouncing pleasure and praising...</p>
        </a>
        <!-- list-group-item -->
      </div>
      <!-- list-group -->
      <span class="d-block pd-15 tx-12">Loading messages...</span>
    </div>
    <!-- #chatMenu -->
    <div id="settingMenu" class="tab-pane">
      <div class="pd-x-15">
        <label class="tx-uppercase tx-11 mg-t-10 tx-orange mg-b-15 tx-medium">Quick Settings</label>
        <div class="bd pd-15">
          <h6 class="tx-13 tx-normal tx-gray-800">Daily Newsletter</h6>
          <p class="tx-12">Get notified when someone else is trying to access your account.</p>
          <div class="toggle toggle-light warning"></div>
        </div>
        <!-- bd -->
        <div class="bd pd-15 mg-t-15">
          <h6 class="tx-13 tx-normal tx-gray-800">Call Phones</h6>
          <p class="tx-12">Make calls to friends and family right from your account.</p>
          <div class="toggle toggle-light warning"></div>
        </div>
        <!-- bd -->
        <div class="bd pd-15 mg-t-15">
          <h6 class="tx-13 tx-normal tx-gray-800">Login Notifications</h6>
          <p class="tx-12">Get notified when someone else is trying to access your account.</p>
          <div class="toggle toggle-light warning"></div>
        </div>
        <!-- bd -->
        <div class="bd pd-15 mg-t-15">
          <h6 class="tx-13 tx-normal tx-gray-800">Phone Approvals</h6>
          <p class="tx-12">Use your phone when login as an extra layer of security.</p>
          <div class="toggle toggle-light warning"></div>
        </div>
        <!-- bd -->
      </div>
    </div>
    <!-- #settingMenu -->
  </div>
  <!-- tab-content -->
</div>