config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"

  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new', as: :log_in
  delete '/logout', to: 'sessions#destroy', as: :log_out

  resources :shoppings, :meals
  resources :staffs do
    member do
      get :add_admin
      get :remove_admin
    end
  end

  scope 'profile' do
    controller :profile do
      get :password
      put :update_password
    end
  end

  resources :departments, :goods, :watch_bills
  resources :books do
    member do
      put :circulate
    end
  end
  get "search", to:  "books#search"

  resources :projects, :quotation_categories, :quotations
  resources :quotation_lists do
    get :update_line_item
    member do
      get :construction_file
      # get :construction_contents
    end

    resources :quotation_list_items, only: [:show, :create, :update, :destroy] do
      member do
        get :add_line_item
        get :remove_line_item
      end
    end

    resources :construction_contents, only: [:index, :create, :destroy]
  end

  resources :roles

  resources :attendances, only: [:index] do
    collection do
      post :excel_import
    end
  end
end

app/models/quotation.rb
class Quotation < ApplicationRecord

  validates :quotation_category0_id, presence: { message: "标准分类不能为空。" }
  validates :quotation_category1_id, presence: { message: "工程分类不能为空。" }
  validates :quotation_category2_id, presence: { message: "设计分类不能为空。" }
  validates :code, presence: { message: "项目编码不能为空。" }
  validates :name, presence: { message: "项目名称不能为空。" }
  validates :material_costs, presence: { message: "材料费不能为空。" }
  validates :labor_costs, presence: { message: "人工费不能为空。" }
  validates :remark, presence: { message: "描述不能为空。" }

  belongs_to :quotation_category, optional: true
end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
  before_action :set_quotation, only: [:show, :edit, :update, :destroy]
  before_action :find_root_categories, only: [:index, :new, :create, :edit, :update]
  before_action :check_role, only: [:edit, :update, :destroy]

  # GET /quotations
  # GET /quotations.json
  def index
    if params[:q] && params[:q][:id].present?
      category_id = params[:q][:id]
      root_category_id = QuotationCategory.find(category_id).root_id
      @q = case root_category_id
          when 1
            Quotation.ransack(quotation_category0_id_eq: category_id)
          when 2
            Quotation.ransack(quotation_category1_id_eq: category_id)
          when 3
            Quotation.ransack(quotation_category2_id_eq: category_id)
          end
      @quotations = @q.result.page(params[:page] || 1).per(params[:per_page] || 20).order(id: "DESC")
    else
      @q = Quotation.ransack(quotation_category0_id_eq: 4)
      @quotations = @q.result.page(params[:page] || 1).per(params[:per_page] || 20).order(id: "DESC")
    end
  end

  # GET /quotations/1
  # GET /quotations/1.json
  def show
  end

  # GET /quotations/new
  def new
    @quotation = Quotation.new
    authorize @quotation
  end

  # GET /quotations/1/edit
  def edit
  end

  # POST /quotations
  # POST /quotations.json
  def create
    @quotation = Quotation.new(quotation_params)
    authorize @quotation
    respond_to do |format|
      if @quotation.save
        format.html { redirect_to @quotation, notice: 'Quotation was successfully created.' }
        format.json { render :show, status: :created, location: @quotation }
      else
        format.html { render :new }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotations/1
  # PATCH/PUT /quotations/1.json
  def update
    respond_to do |format|
      if @quotation.update(quotation_params)
        format.html { redirect_to @quotation, notice: 'Quotation was successfully updated.' }
        format.json { render :show, status: :ok, location: @quotation }
      else
        format.html { render :edit }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotations/1
  # DELETE /quotations/1.json
  def destroy
    @quotation.destroy
    respond_to do |format|
      format.html { redirect_to quotations_url, notice: 'Quotation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quotation
      @quotation = Quotation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quotation_params
      params.require(:quotation).permit!
    end

    def find_root_categories
      @root_categories = QuotationCategory.roots.order(created_at: "ASC")
    end

    def check_role
      authorize @quotation
    end
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/views/quotations/_form.html.erb
<div class="am-pagebody">
  <div class="card pd-20 pd-sm-40">
    <h6 class="card-body-title"><%= @quotation.new_record? ? "新建" : "修改 ##{params[:id]}" %></h6>
    <% if quotation.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(quotation.errors.count, "error") %> prohibited this quotation from being saved:</h2>

        <ul>
        <% quotation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_with(model: quotation, local: true, class: "form-layout") do |f| %>
      <div class="row mg-b-25">
        <div class="col-lg-4">
          <div class="form-group">
            <label class="form-control-label">项目编码: <span class="tx-danger">*</span></label>
            <%= f.text_field :code, class: "form-control" %>
          </div>
        </div>

        <div class="col-lg-4">
          <div class="form-group">
            <label class="form-control-label">项目名称: <span class="tx-danger">*</span></label>
            <%= f.text_field :name, class: "form-control" %>
          </div>
        </div>

        <div class="col-lg-4">
          <div class="form-group">
            <label class="form-control-label">单位: <span class="tx-danger">*</span></label>
            <%= f.text_field :unit, class: "form-control" %>
          </div>
        </div>

        <div class="col-lg-4">
          <div class="form-group">
            <label class="form-control-label">材料费: <span class="tx-danger">*</span></label>
            <%= f.number_field :material_costs, class: "form-control", step: :any %>
          </div>
        </div>

        <div class="col-lg-4">
          <div class="form-group">
            <label class="form-control-label">人工费: <span class="tx-danger">*</span></label>
            <%= f.number_field :labor_costs, class: "form-control", step: :any %>
          </div>
        </div>

        <div class="col-lg-4">
          <div class="form-group">
            <label class="form-control-label">合 价: <span class="tx-danger">*</span></label>
            <%= f.number_field :total_amount, class: "form-control", step: :any %>
          </div>
        </div>

        <% @root_categories.each_with_index do |category, index| %>
          <div class="col-lg-4">
            <div class="form-group">
              <label for="category_id" class="form-control-label">按<%= category.title %>: <span class="tx-danger">*</span></label>
              <select name="quotation[quotation_category<%= index %>_id]" class="form-control select2" data-placeholder="选择分类">
                  <option label="Choose one"></option>
                  <% category.children.each do |sub_category| %>
                    <option value="<%= sub_category.id %>" <%= sub_category.id == @quotation["quotation_category#{index}_id"] ? 'selected' : '' %>><%= sub_category.title %></option>
                  <% end -%>
              </select>
            </div>
          </div>
        <% end -%>

        <div class="col-lg-8">
          <div class="form-group mg-b-10-force">
            <label class="form-control-label">材料及工艺要求: <span class="tx-danger">*</span></label>
            <%= f.text_area :remark, class: "form-control", rows: 5, placeholder: "输入材料及工艺要求" %>
          </div>
        </div>
      </div>
      <div class="form-layout-footer">
        <%= f.submit "确 定", class: "btn btn-info" %>
      </div>
    <% end %>
  </div>
</div>

app/views/quotations/edit.html.erb
<% provide(:title, "修改报价条目") %>

<%= render 'form', quotation: @quotation %>

app/views/quotations/index.html.erb
<% provide(:title, "装饰报价总表") %>
<%= content_for :stylesheets do %>
  <style>
    .wd-select {
      width: 500px;
    }
  </style>
<% end %>

<div class="am-pagebody">
  <div class="card pd-20">
    <h6 class="card-body-title">装饰报价总表</h6>
    <p class="mg-b-20 mg-sm-b-30">爱上家装饰报价总表</p>
    <%= search_form_for @q do |f| %>
      <div class="d-md-flex">
        <div id="slWrapper" class="parsley-select wd-select">
          <select name="q[id]" class="form-control select2" data-placeholder="选择分类">
            <option label="Choose one"></option>
            <% @root_categories.each do |category| %>
              <optgroup label="> <%= category.title %>"></optgroup>

              <% category.children.each do |sub_category| %>
                <option value="<%= sub_category.id %>" %>>> <%= sub_category.title %></option>
              <% end -%>
            <% end -%>
          </select>
        </div>

        <div class="mg-md-l-10 mg-t-10 mg-md-t-0">
          <%= f.submit "搜索", class: "btn btn-info pd-x-15"%>
        </div>
        <div class="mg-md-l-100 mg-t-10 mg-md-t-0">
          <a href="<%= new_quotation_path %>" class="btn btn-primary">添加</a>
        </div>
      </div>
    <% end %>
    <br>
    <div class="table-responsive">
      <table class="table table-hover table-bordered mg-b-0">
        <thead class="bg-info">
          <tr>
            <th>序号</th>
            <th>项目编码</th>
            <th>项目名称</th>
            <th>单位</th>
            <th>数量</th>
            <th>材料费</th>
            <th>人工费</th>
            <th>合计</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <% @quotations.each_with_index do |quotation, index| %>
            <tr>
              <td><%= index + 1 %></td>
              <td><%= quotation.code %></td>
              <td><%= quotation.name %></td>
              <td><%= quotation.unit %></td>
              <td><%= quotation.quantity %></td>
              <td><%= quotation.material_costs %></td>
              <td><%= quotation.labor_costs %></td>
              <td><%= quotation.total_amount %></td>
              <td>
                <%= link_to '查看', quotation %>
                <%= link_to '编辑', edit_quotation_path(quotation) %>
                <%= link_to '删除', quotation, method: :delete, data: { confirm: 'Are you sure?' } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <%= paginate @quotations %>
    </div>
  </div>
</div>

app/views/quotations/new.html.erb
<% provide(:title, "新建报价条目") %>

<%= render 'form', quotation: @quotation %>

app/views/quotations/show.html.erb
<% provide(:title, "查看信息") %>

<div class="am-pagebody">
  <div class="card pd-20 pd-sm-40">
    <h6 class="card-body-title"><span class="tx-danger"><%= @quotation.name %></span>的详情</h6>
    <p class="mg-b-20 mg-sm-b-30">资料详情展示</p>
    <div class="row mg-b-20">
      <div class="col-md-3">
        <div class="card rounded-0">
          <div class="card-header card-header-default">
            项目编码
          </div>
          <div class="card-body bg-gray-200">
            <p class="mg-b-0"><%= @quotation.code %></p>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card rounded-0">
          <div class="card-header card-header-default">
            项目名称
          </div>
          <div class="card-body bg-gray-200">
            <p class="mg-b-0"><%= @quotation.name %></p>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card rounded-0">
          <div class="card-header card-header-default">
            单位
          </div>
          <div class="card-body bg-gray-200">
            <p class="mg-b-0"><%= @quotation.unit %></p>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card rounded-0">
          <div class="card-header card-header-default">
            材料费
          </div>
          <div class="card-body bg-gray-200">
            <p class="mg-b-0"><%= @quotation.material_costs %></p>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card rounded-0">
          <div class="card-header card-header-default">
            人工费
          </div>
          <div class="card-body bg-gray-200">
            <p class="mg-b-0"><%= @quotation.labor_costs %></p>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card rounded-0">
          <div class="card-header card-header-default">
            合计
          </div>
          <div class="card-body bg-gray-200">
            <p class="mg-b-0"><%= @quotation.total_amount %></p>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="card rounded-0">
          <div class="card-header card-header-default">
            材料及工艺要求
          </div>
          <div class="card-body bg-gray-200">
            <p class="mg-b-0"><%= @quotation.remark %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="form-layout-footer">
      <%= link_to '编辑', edit_quotation_path(@quotation), class: "btn btn-info mg-r-5" %>
      <%= link_to '返回', quotations_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>